module.exports = {
  purge: {
    content: [
      './pages/**/*.{js,ts,jsx,tsx}',
      './components/**/*.{js,ts,jsx,tsx}',
    ],
    options: {
      safelist: [
        'bg-pink-600',
        'bg-pink-100',
        'hover:bg-pink-100',
        'bg-green-600',
        'bg-green-100',
        'hover:bg-green-100',
        'bg-blue-600',
        'bg-blue-100',
        'hover:bg-blue-100',
        'bg-indigo-600',
        'bg-indigo-100',
        'hover:bg-indigo-100',
        'bg-yellow-600',
        'bg-yellow-100',
        'hover:bg-yellow-100',
        'w-24',
        'w-28',
        'w-32',
        'w-36',
        'w-40',
        'w-44',
        'w-48',
        'w-52',
        'w-56',
        'w-60',
        'w-64',
        'h-24',
        'h-28',
        'h-32',
        'h-36',
        'h-40',
        'h-44',
        'h-48',
        'h-52',
        'h-56',
        'h-60',
        'h-64',
      ],
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
